server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: ms-productos
          uri: lb://ms-productos
          predicates:
            - Path=/api/productos/**,/api/categorias/**
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/permissions/**,/api/roles/**,/api/userroles/**,/api/rolespermisos/**,/api/usuarios/**

jwt:
  secret: MiClaveSecretaSuperLargaYSeguraQueTieneAlMenos512BitsDeLongitud

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
